spring:
  application.name: events-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # Use Specific Record or else you get Avro GenericRecord.
      specific.avro.reader: true
      auto.offset.reset: earliest
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081

